# Generated by Django 2.2.4 on 2019-10-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191006_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popsticle',
        ),
    ]
