# Generated by Django 2.2.4 on 2019-09-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='players',
        ),
    ]
